import LoginPage from "./pages/login-page";
import SignupPage from "./pages/signup-page";
import UserProfilePage from "./pages/user-profile-page";
import "./App.css";

function App() {
  return (
    <div className="sheet">
      <div className="sheet-header">
        <div className="kicker">CODEFORGE AI — AUTONOMOUS AI CTO</div>
        <h1>System Console</h1>
        <p>
          Interfaces generated by the Frontend and Backend agents, wired
          together by DevOps.
        </p>
      </div>

      <SignupPage />
      <div className="flow-line" />
      <LoginPage />
      <div className="flow-line" />
      <UserProfilePage />

      <div className="title-block">
        <span>MODULES: M04 · M05 · M06</span>
        <span>REV. 01</span>
      </div>
    </div>
  );
}

export default App;
