import SignupPage from './pages/SignupPage';
import LoginPage from './pages/LoginPage';
import UserProfilePage from './pages/UserProfilePage';
import './App.css';

function App() {
  return (
    <div className="sheet">
      <div className="sheet-header">
        <div className="kicker">CODEFORGE AI — AUTONOMOUS AI CTO</div>
        <h1>System Console</h1>
        <p>Interfaces generated by the Frontend and Backend agents, wired together by DevOps.</p>
      </div>

      <SignupPage />
      <div className="flow-line"></div>
      <LoginPage />
      <div className="flow-line"></div>
      <UserProfilePage />

      <div className="title-block">
        <span>MODULES: M04 · M05 · M06</span>
        <span>REV. 01</span>
      </div>
    </div>
  );
}

export default App;